integrated backend API into Sign in and Signup forms
Code-the-Dream-School/bb-practicum-team-3-front pull request #3
Opened 2023-04-10 22:03 UTC by marinacod

## Description

Sign up
Sent a post request to server for "/register" endpoint, redirect a user to Home page if registration is successful 
Sign in
send a post request to server, endpoint "/login", if successful, redirect to Home page 

## Acceptance Criteria

Make the signup route functional with backend auth
Once you receive the response 200 direct the user to the Home page
When Login is successful direct the user to the Home page

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Testing Steps / QA Criteria

start the back-end server first 
open “bb-practicum-bb-front-3” 
run npm start to start the development server
open http://localhost:3000/ with your browser
click “Sign up” button in Header section
enter valid credentials (password should be at least 6 characters long) 
click on the 'Sign up' button (if successful, it should direct the user to the Home page)
click “Sign in”  button in Header section 
enter valid credentials  (if successful, it should direct the user to the Home page)

2023-04-10 23:18 UTC, madebymiguel requested changes
Looks good to me

2023-04-10 23:18 UTC, madebymiguel commented on src/api/fetchSignup.js
> +  console.log(JSON.stringify(signUpData));
Remove console.log()

2023-04-14 20:48 UTC, madebymiguel approved these changes
Looks good to me

2023-04-15 00:46 UTC, OxanaMl commented
Everything looks good

2023-04-15 00:51 UTC, OxanaMl approved these changes
Everything looks good

2023-04-15 00:52 UTC, merged