Maryna image gallery
Code-the-Dream-School/bb-practicum-team-3-front pull request #4
Opened 2023-04-11 00:25 UTC by marinacod

## Description

Added a responsive image gallery to Home page

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Updates

### Before

### After
https://ibb.co/JRQcbtx

## Testing Steps / QA Criteria

2023-04-25 01:14 UTC, madebymiguel requested changes
Overall looks good

2023-04-25 01:14 UTC, madebymiguel commented on src/components/PopularDestinationGrid.js
Needs some margin bottom for when its in mobile view. Footer covers some of it

2023-04-25 01:14 UTC, madebymiguel commented on src/components/PopularDestinationGrid.js
Also needs for a more visual indicator that the user can click the grid item. Probably a hover effect with a thin color border

2023-04-25 02:34 UTC, madebymiguel approved these changes

2023-04-25 02:34 UTC, madebymiguel approved these changes

2023-04-25 08:34 UTC, OxanaMl approved these changes
Looks good

2023-04-26 02:59 UTC, alton-michaux approved these changes
Looks good @marinacod 👍🏾

2023-04-26 03:09 UTC, merged